// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import sitemap from '@astrojs/sitemap';
import { SITE, REPO } from './src/site.ts';
import { lastmodFor } from './src/lastmod.ts';

// The one place the stack is deliberately not Go (PRD §9). The Go decision was
// about the binary — single static artifact, no runtime, hydrate is CPU-bound —
// and none of that reasoning applies to a documentation site. Astro Starlight is
// purpose-built for docs plus a landing page, and it deploys onto the Cloudflare
// Pages standard the rest of this org already uses.
//
// https://astro.build/config
export default defineConfig({
	site: SITE,
	integrations: [
		// Declared explicitly so it can be configured. Starlight adds
		// `@astrojs/sitemap` on its own ONLY when the integration is not already
		// present, so listing it here replaces its default rather than duplicating
		// it — the sitemap was previously a bare list of 49 <loc> elements with no
		// <lastmod>, which tells a crawler nothing about what is worth re-fetching.
		sitemap({
			serialize(item) {
				// The date is the git commit date of the page's source, from
				// src/generated/lastmod.json. A route with no entry (added but not yet
				// committed) simply gets no <lastmod>: an absent date costs a hint, a
				// wrong one spends trust.
				const lastmod = lastmodFor(new URL(item.url).pathname);
				return lastmod ? { ...item, lastmod } : item;
			},
		}),
		starlight({
			title: 'rowshape',
			description:
				'The type-checker for database migrations — a human and an agent get the same answer through the same contract.',
			// Decouples the <title> tag from the page heading and de-duplicates the
			// homepage title. See the file for why both are needed.
			routeMiddleware: './src/starlightRouteData.ts',
			social: [
				{ icon: 'github', label: 'GitHub', href: REPO },
			],
			// The social card. Starlight already emits twitter:card=summary_large_image
			// on every page, which without an image renders as a blank rectangle
			// wherever a link is shared — Slack, X, LinkedIn, Discord, and the link
			// previews inside the agent tooling this project is aimed at.
			//
			// One site-wide card rather than per-page generated ones: a per-page
			// image means rasterizing text at build time, which depends on the CI
			// runner's fonts and fails by silently rendering nothing. public/og.png is
			// generated by `npm run og` and committed, so the artifact is reviewable.
			//
			// og:image must be absolute — a relative one is ignored by every scraper.
			head: [
				{ tag: 'meta', attrs: { property: 'og:image', content: `${SITE}/og.png` } },
				{ tag: 'meta', attrs: { property: 'og:image:type', content: 'image/png' } },
				{ tag: 'meta', attrs: { property: 'og:image:width', content: '1200' } },
				{ tag: 'meta', attrs: { property: 'og:image:height', content: '630' } },
				{
					tag: 'meta',
					attrs: {
						property: 'og:image:alt',
						content:
							'rowshape — the type-checker for database migrations. A terminal showing `rowshape validate` returning FAIL RS-LOCK-001: ACCESS EXCLUSIVE on users, ~4m.',
					},
				},
				{ tag: 'meta', attrs: { name: 'twitter:image', content: `${SITE}/og.png` } },
			],
			editLink: {
				baseUrl: `${REPO}/edit/main/docs-site/`,
			},
			// The sections the docs are organized around. Content lands in P4-T4
			// (install, findings, privacy) and P4-T5 (agents/MCP, fixture spec); this
			// is the shape it lands into.
			sidebar: [
				{ label: 'Install', items: [{ autogenerate: { directory: 'install' } }] },
				// Generated from the cobra tree by `go run ./tools/gencli`, with a
				// staleness test, so the reference cannot drift from the binary.
				{ label: 'CLI reference', items: [{ autogenerate: { directory: 'reference' } }] },
				{ label: 'Findings', items: [{ autogenerate: { directory: 'findings' } }] },
				{ label: 'Privacy', items: [{ autogenerate: { directory: 'privacy' } }] },
				// What the tool can and cannot know. PRD §14 committed to saying this
				// in the docs ("Fixture fidelity is a tarpit ... Say so in the docs")
				// and the page did not exist until CR4-T13.
				{ label: 'Fidelity', items: [{ autogenerate: { directory: 'fidelity' } }] },
				{ label: 'Agents & MCP', items: [{ autogenerate: { directory: 'agent' } }] },
				{ label: 'Fixture spec', items: [{ autogenerate: { directory: 'spec' } }] },
			],
		}),
	],
});
