import data from './generated/lastmod.json';

/**
 * Route -> ISO 8601 commit date, generated by scripts/gen-lastmod.mjs before
 * every build.
 *
 * A route can be absent: a page added and not yet committed has no git date, and
 * omitting it is honest where guessing is not. Callers must treat `undefined` as
 * "do not claim a date" rather than substituting now.
 */
export const lastmod: Record<string, string> = data.dates ?? {};

export function lastmodFor(pathname: string): string | undefined {
	return lastmod[pathname.endsWith('/') ? pathname : `${pathname}/`];
}
