package profile

import (
	"context"
	"testing"

	"github.com/jackc/pgx/v5"
)

const defSchema = "rowshape_default_test"

func seedDefaults(t *testing.T, conn *pgx.Conn) {
	t.Helper()
	ctx := context.Background()
	stmts := []string{
		`DROP SCHEMA IF EXISTS ` + defSchema + ` CASCADE`,
		`CREATE SCHEMA ` + defSchema,
		`CREATE TABLE ` + defSchema + `.orders (
			id       bigserial PRIMARY KEY,
			ident    bigint GENERATED BY DEFAULT AS IDENTITY,
			payload  jsonb NOT NULL DEFAULT '{}'::jsonb,
			status   text NOT NULL DEFAULT 'pending',
			plain    text,
			total    numeric(12,2) GENERATED ALWAYS AS (1 + 1) STORED
		)`,
		`INSERT INTO ` + defSchema + `.orders (plain) SELECT 'x' || g FROM generate_series(1, 100) g`,
		`ANALYZE ` + defSchema + `.orders`,
	}
	for _, s := range stmts {
		if _, err := conn.Exec(ctx, s); err != nil {
			t.Fatalf("seed defaults (%s): %v", s, err)
		}
	}
	t.Cleanup(func() {
		_, _ = conn.Exec(context.Background(), `DROP SCHEMA IF EXISTS `+defSchema+` CASCADE`)
	})
}

// TestPullRecordsColumnDefaults is the wrong-FAIL regression. A bare NOT NULL in
// the target where production has NOT NULL DEFAULT made every INSERT that omits
// the column fail there and succeed in production.
func TestPullRecordsColumnDefaults(t *testing.T) {
	conn := adminConn(t)
	seedDefaults(t, conn)

	f, err := Fast(context.Background(), conn, Options{Schemas: []string{defSchema}})
	if err != nil {
		t.Fatalf("Fast: %v", err)
	}
	cols := f.Tables[defSchema+".orders"].Columns

	if got := cols["payload"].Default; got == "" {
		t.Error("payload: DEFAULT not recorded")
	}
	if got := cols["status"].Default; got == "" {
		t.Error("status: DEFAULT not recorded")
	}
	// A serial column IS an ordinary column with a nextval default, and recording it
	// is what lets the target recreate the sequence rather than fail on it.
	if got := cols["id"].Default; got == "" {
		t.Error("serial column: nextval default not recorded")
	}
	// A column with no default carries none, so the field stays absent in ordinary
	// fixtures.
	if got := cols["plain"].Default; got != "" {
		t.Errorf("plain: unexpected default %q", got)
	}
	// An identity column's implicit sequence default must NOT surface as a DEFAULT —
	// `generated` already carries it, and it would name a sequence the target lacks.
	if got := cols["ident"].Default; got != "" {
		t.Errorf("identity column carries a default %q", got)
	}
	// Nor may a generated column's expression land in `default`.
	if got := cols["total"].Default; got != "" {
		t.Errorf("generated column carries a default %q", got)
	}
	if cols["total"].GeneratedExpression == "" {
		t.Error("generated column lost its expression")
	}
}

// TestStrictPrivacyMakesDefaultOpaque: a DEFAULT is DDL of the same class as a
// CHECK and can embed a literal from the business domain, so strict withholds it.
func TestStrictPrivacyMakesDefaultOpaque(t *testing.T) {
	conn := adminConn(t)
	seedDefaults(t, conn)

	f, err := Fast(context.Background(), conn, Options{Schemas: []string{defSchema}, Privacy: PrivacyStrict})
	if err != nil {
		t.Fatalf("Fast: %v", err)
	}
	ApplyPrivacy(f, PrivacyStrict, 0)

	if got := f.Tables[defSchema+".orders"].Columns["status"].Default; got != "opaque" {
		t.Errorf("default under strict = %q, want \"opaque\"", got)
	}
}
