package profile

import (
	"context"
	"testing"

	"github.com/jackc/pgx/v5"
)

const genSchema = "rowshape_gen_test"

func seedGenerated(t *testing.T, conn *pgx.Conn) {
	t.Helper()
	ctx := context.Background()
	stmts := []string{
		`DROP SCHEMA IF EXISTS ` + genSchema + ` CASCADE`,
		`CREATE SCHEMA ` + genSchema,
		`CREATE TABLE ` + genSchema + `.orders (
			id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			strict_id bigint GENERATED ALWAYS AS IDENTITY,
			subtotal numeric(12,2) NOT NULL,
			tax      numeric(12,2) NOT NULL DEFAULT 0,
			total    numeric(12,2) GENERATED ALWAYS AS (subtotal + tax) STORED
		)`,
		`INSERT INTO ` + genSchema + `.orders (subtotal, tax)
		   SELECT g, 1 FROM generate_series(1, 200) g`,
		`ANALYZE ` + genSchema + `.orders`,
	}
	for _, s := range stmts {
		if _, err := conn.Exec(ctx, s); err != nil {
			t.Fatalf("seed generated (%s): %v", s, err)
		}
	}
	t.Cleanup(func() {
		_, _ = conn.Exec(context.Background(), `DROP SCHEMA IF EXISTS `+genSchema+` CASCADE`)
	})
}

// TestPullRecordsGeneratedColumns: `generated: stored` alone says a column is
// computed but not FROM WHAT, so a consumer rebuilt it as an ordinary column and
// the target accepted an UPDATE that production rejects with `column "total" can
// only be updated to DEFAULT`. And ALWAYS vs BY DEFAULT decides whether an
// explicit value in an INSERT is accepted at all.
func TestPullRecordsGeneratedColumns(t *testing.T) {
	conn := adminConn(t)
	seedGenerated(t, conn)

	f, err := Fast(context.Background(), conn, Options{Schemas: []string{genSchema}})
	if err != nil {
		t.Fatalf("Fast: %v", err)
	}
	cols := f.Tables[genSchema+".orders"].Columns

	if got := cols["id"]; got.Generated != "identity" || got.Identity != "by_default" {
		t.Errorf("id: generated=%q identity=%q, want identity/by_default", got.Generated, got.Identity)
	}
	if got := cols["strict_id"]; got.Generated != "identity" || got.Identity != "always" {
		t.Errorf("strict_id: generated=%q identity=%q, want identity/always", got.Generated, got.Identity)
	}
	total := cols["total"]
	if total.Generated != "stored" {
		t.Errorf("total: generated=%q, want stored", total.Generated)
	}
	if total.GeneratedExpression == "" {
		t.Error("total: no generation expression recorded; a consumer cannot recreate the column")
	}

	// An identity column's implicit sequence default must not leak in as a
	// generation expression: it would name a sequence the target does not have.
	if cols["id"].GeneratedExpression != "" {
		t.Errorf("identity column carries a generation expression %q", cols["id"].GeneratedExpression)
	}
	// An ordinary column with a DEFAULT is not a generated column.
	if cols["tax"].Generated != "" || cols["tax"].GeneratedExpression != "" {
		t.Errorf("defaulted column reported as generated: %+v", cols["tax"])
	}
}

// TestStrictPrivacyMakesGenerationExpressionOpaque: the expression is DDL that can
// name business logic, exactly like a CHECK (§6.4), so it gets the same treatment
// — while `generated: stored` survives, so a consumer still knows the column is
// computed and can report that it cannot reproduce it.
func TestStrictPrivacyMakesGenerationExpressionOpaque(t *testing.T) {
	conn := adminConn(t)
	seedGenerated(t, conn)

	f, err := Fast(context.Background(), conn, Options{Schemas: []string{genSchema}, Privacy: PrivacyStrict})
	if err != nil {
		t.Fatalf("Fast: %v", err)
	}
	ApplyPrivacy(f, PrivacyStrict, 0)

	total := f.Tables[genSchema+".orders"].Columns["total"]
	if total.GeneratedExpression != "opaque" {
		t.Errorf("generation expression under strict = %q, want \"opaque\"", total.GeneratedExpression)
	}
	if total.Generated != "stored" {
		t.Errorf("generated kind lost under strict: %q", total.Generated)
	}
}
